version: '3.8'

services:

    # Backend API
    smart-brain-api:
        container_name: backend
        # image: node:8.11.1
        build: ./
        command: npm start -- -L
        working_dir: /usr/src/smart-brain-api-1
        environment:
            POSTGRES_URI: postgres://postgres:secret@postgres:5432/smart-brain-docker
        links:
            - postgres
        ports: 
            - "3000:3000"
        volumes: 
            - ./:/usr/src/smart-brain-api-1


    # Postgres
    postgres:
        environment:
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: secret
            POSTGRES_DB: smart-brain-docker
            POSTGRES_HOST: postgres
        container_name: postgres
        build: ./postgres
        ports: 
            - "5432:5432"   
        # environment:
        #     POSTGRES_USER: 'postgres'
        #     POSTGRES_PASSWORD: 'Naminam87'     
        